## Importing the Libraries

In [6]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

## Loading the dataset

Loading the shuffled dataset in CSV format named willow_creek_may_sept_shuffled.csv



In [14]:
#Load Dataset
df = pd.read_csv("willow_creek_may_sept_shuffled.csv")
dataset = df.values

#Split into 5 Input(X) and 1 output (Y) variables
X = dataset[:, 0:5]
Y = dataset[:,5]
#print(X)

[[ 23.4 240.    8.4   8.9   1.6]
 [ 21.3 244.    7.2   8.7   2.7]
 [ 25.8 241.    8.6   8.9   1.2]
 ...
 [ 22.5 229.    9.5   9.    0.6]
 [ 23.4 242.    8.    8.8   1.7]
 [ 21.7 225.    9.7   8.9   0.8]]
